import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillFacebook,
  AiFillGithub
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/my.png";
import code from "../public/code.png";
import design from "../public/design.png";
import web from "../public/web.png";
import Image from "next/image";
import filepic from "../public/filepic.png";
import fireball from "../public/fireball.png";
import webpic from "../public/webpic.png";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section id="about" className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">My SiTe</h1>
            <ul className="flex items-center space-x-6">
              <li>
                <a href="#about" className="hover:text-custom-500">About Me</a>
              </li>
              <li>
                <a href="#skills" className="hover:text-custom-500">Skills</a>
              </li>
              <li>
                <a href="#projects" className="hover:text-custom-500">Projects</a>
              </li>
              <li>
                <a href="#contact" className="hover:text-custom-500">Contact Me</a>
              </li>
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-custom-500 font-medium dark:text-custom-500 md:text-6xl">
              Muskan Rehan
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Student | Programmer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-600 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I am a passionate computer science student at Habib University with a keen interest in web development and programming.

              On this site, you'll find a collection of my projects, showcasing my skills in web development, programming, and more. Come on, let me walk you through some of them!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.linkedin.com/in/muskan-rehan-159367261/" className="hover:text-custom-500" >
                <AiFillLinkedin />

              </a>
              <a href="https://www.facebook.com/share/5tWhGaCHe4nAJKAR/?mibextid=qi2Omg" className="hover:text-custom-500" >
                <AiFillFacebook />
              </a>
              <a href="https://github.com/Muskan865" className="hover:text-custom-500" >
                <AiFillGithub />
              </a>


            </div>
            <div className="mt-8 ">
              <a
                className="bg-gradient-to-r from-custom-500 text- to-custom-500 text-white px-4 py-2 border-none rounded-md ml-8 hover:text-black"
                href="https://drive.google.com/file/d/1M3S374c-LhWkmM2_WC2q9hk3ZsEwjdVL/view?usp=drive_link"
              >
                Resume
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-custom-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section id="skills">
          <div className=" text-center p-10 py-10">
            <h3 className="text-3xl py-1 text-custom-500 dark:text-white ">My Skills</h3>
            <p className="text-md py-5 leading-8 text-gray-600 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              My fascination with technology is matched only by my passion for chess, where every game is a blend of strategy, foresight, and creativity—qualities I bring into my coding projects. Whether it's a sleek and responsive website, a complex algorithm, or a strategic game plan, I bring dedication and creativity to everything I do.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Programming
              </h3>
              <p className="py-2">
                Want to transforming ideas into innovative solutions? Well I'm the man (or rather the woman 😉 )
              </p>
              <h4 className="py-4 text-custom-500">Languages I Use</h4>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">C++</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">HTML/CSS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={web} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Web Development
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's turn it into a
                reality!
              </p>
              <h4 className="py-4 text-custom-500">Tools I Use</h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1"> CSS</p>
              <p className="text-gray-800 py-1">javaScript</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Designing</h3>
              <p className="py-2">
                Lets enjoy exploring design tools to create visually appealing graphics and materials.
              </p>
              <h4 className="py-4 text-custom-500">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Canva</p>
            </div>
          </div>
        </section>

        {/* Projects Section */}
        <section id="projects" className="py-10">
          <div className=" text-center p-10 py-10">
            <h3 className="text-3xl py-1 text-custom-500 dark:text-white ">Projects</h3>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap basis-1/3 ">
              <Image className="rounded-lg object-cover" src={filepic} width={300} height={200} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                File Compression Algorithm
              </h3>
              <p className="py-2">
                I designed a text compression algorithm which can operate in minimal time complexity. It was a project I made inspired by the huffman algorithm and this project helped me acquire a better understanding of tree implementation using python.
              </p>
              <a
                className="bg-gradient-to-r from-custom-500 text- to-custom-500 text-white px-4 pt-3 border-none rounded-md ml-8 hover:text-black"
                href="https://github.com/Muskan865/file-compression-decompression"
              >
                View Project
              </a>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap basis-1/3 ">
              <Image className="rounded-lg object-cover" src={fireball} width={300} height={220} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Lava Fury: The Dodger's Challenge
              </h3>
              <p className="py-2">
                Who doesn't love playing games right? So I decided to design my own game in Python. It is an interesting game and the difficulty increases with time as the speed of the game increases! If you want to check it out be sure to click on the github button.
              </p>
              <a
                className="bg-gradient-to-r from-custom-500 text- to-custom-500 text-white px-4 pt-3 border-none rounded-md ml-8 hover:text-black"
                href="https://github.com/Muskan865/python-game"
              >
                View Project
              </a>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap basis-1/3 ">
              <Image className="rounded-lg object-cover" src={webpic} width={300} height={220} alt="here" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Custom Website
              </h3>
              <p className="py-2">
                I designed my very own personal website from scratch using custom css and html. Even though it's a basic website, it showcases my proficiency in html, css and java script which are essential for a web developer.
              </p>
              <a
                className="bg-gradient-to-r from-custom-500 text- to-custom-500 text-white px-4 pt-3 border-none rounded-md ml-8 hover:text-black"
                href="https://muskan865.github.io/portfolio-website/"
              >
                View Project
              </a>
            </div>

          </div>
        </section>

        {/* Contact Me Section */}
        <section id="contact" className="py-10">
          <div className="text-center p-10 py-10">
            <h3 className="text-3xl py-1 text-custom-500 dark:text-white">Contact Me</h3>
            <p className="text-md py-5 leading-8 text-gray-600 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I would love to hear from you! Whether you have a question, a project opportunity, or just want to connect, feel free to drop me a message using the button below. I will get back to you as soon as possible.
            </p>
            <a href="mailto:muskanrehan865@gmail.com">
              <button
                type="button"
                className="bg-gradient-to-r from-custom-500 to-custom-500 text-white px-4 py-2 border-none rounded-md hover:text-black"
              >
                Email Me
              </button>
            </a>
          </div>
        </section>

      </main>
    </div>
  );
}
